version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    image: spring-app
    container_name: spring-backend
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

  frontend:
    image: angular-app
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
